export const ActionTypes = {

  /**********************************AUTH CONSTANTS**********************************/
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",

  REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_ERROR: "REGISTER_USER_ERROR",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_ERROR: "FORGOT_PASSWORD_ERROR",

  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",

  /**********************************BANK ACCOUNTS CONSTANTS**********************************/

  FETCH_CUSTOMER_BANK_ACCOUNTS_REQUEST: "FETCH_CUSTOMER_BANK_ACCOUNTS_REQUEST",
  FETCH_CUSTOMER_BANK_ACCOUNTS_SUCCESS: "FETCH_CUSTOMER_BANK_ACCOUNTS_SUCCESS",
  FETCH_CUSTOMER_BANK_ACCOUNTS_ERROR: "FETCH_CUSTOMER_BANK_ACCOUNTS_ERROR",

  FETCH_BANK_ACCOUNT_REQUEST: "FETCH_BANK_ACCOUNT_REQUEST",
  FETCH_BANK_ACCOUNT_SUCCESS: "FETCH_BANK_ACCOUNT_SUCCESS",
  FETCH_BANK_ACCOUNT_ERROR: "FETCH_BANK_ACCOUNT_ERROR",

  FETCH_RECIPIENT_BANK_ACCOUNT_REQUEST: "FETCH_RECIPIENT_BANK_ACCOUNT_REQUEST",
  FETCH_RECIPIENT_BANK_ACCOUNT_SUCCESS: "FETCH_RECIPIENT_BANK_ACCOUNT_SUCCESS",
  FETCH_RECIPIENT_BANK_ACCOUNT_ERROR: "FETCH_RECIPIENT_BANK_ACCOUNT_ERROR",

  CREATE_BANK_ACCOUNT_REQUEST: "CREATE_BANK_ACCOUNT_REQUEST",
  CREATE_BANK_ACCOUNT_SUCCESS: "CREATE_BANK_ACCOUNT_SUCCESS",
  CREATE_BANK_ACCOUNT_ERROR: "CREATE_BANK_ACCOUNT_ERROR",

  UPDATE_BANK_ACCOUNT_REQUEST: "UPDATE_BANK_ACCOUNT_REQUEST",
  UPDATE_BANK_ACCOUNT_SUCCESS: "UPDATE_BANK_ACCOUNT_SUCCESS",
  UPDATE_BANK_ACCOUNT_ERROR: "UPDATE_BANK_ACCOUNT_ERROR",

  /**********************************ADDRESS CONSTANTS**********************************/
  FETCH_ADDRESSES_REQUEST: "FETCH_ADDRESSES_REQUEST",
  FETCH_ADDRESSES_SUCCESS: "FETCH_ADDRESSES_SUCCESS",
  FETCH_ADDRESSES_ERROR: "FETCH_ADDRESSES_ERROR",

  FETCH_ADDRESS_REQUEST: "FETCH_ADDRESS_REQUEST",
  FETCH_ADDRESS_SUCCESS: "FETCH_ADDRESS_SUCCESS",
  FETCH_ADDRESS_ERROR: "FETCH_ADDRESS_ERROR",

  CREATE_ADDRESS_REQUEST: "CREATE_ADDRESS_REQUEST",
  CREATE_ADDRESS_SUCCESS: "CREATE_ADDRESS_SUCCESS",
  CREATE_ADDRESS_ERROR: "CREATE_ADDRESS_ERROR",

  UPDATE_ADDRESS_REQUEST: "UPDATE_ADDRESS_REQUEST",
  UPDATE_ADDRESS_SUCCESS: "UPDATE_ADDRESS_SUCCESS",
  UPDATE_ADDRESS_ERROR: "UPDATE_ADDRESS_ERROR",

  /****************************BRANCHES**********************************/
  FETCH_BRANCHES_REQUEST: "FETCH_BRANCHES_REQUEST",
  FETCH_BRANCHES_SUCCESS: "FETCH_BRANCHES_SUCCESS",
  FETCH_BRANCHES_ERROR: "FETCH_BRANCHES_ERROR",

  FETCH_BRANCH_REQUEST: "FETCH_BRANCH_REQUEST",
  FETCH_BRANCH_SUCCESS: "FETCH_BRANCH_SUCCESS",
  FETCH_BRANCH_ERROR: "FETCH_BRANCH_ERROR",

  CREATE_BRANCH_REQUEST: "CREATE_BRANCH_REQUEST",
  CREATE_BRANCH_SUCCESS: "CREATE_BRANCH_SUCCESS",
  CREATE_BRANCH_ERROR: "CREATE_BRANCH_ERROR",

  UPDATE_BRANCH_REQUEST: "UPDATE_BRANCH_REQUEST",
  UPDATE_BRANCH_SUCCESS: "UPDATE_BRANCH_SUCCESS",
  UPDATE_BRANCH_ERROR: "UPDATE_BRANCH_ERROR",

  /***********************************CASH TRANSACTIONS CONSTANTS**********************************/
  FETCH_ACCOUNT_CASH_TRANSACTIONS_REQUEST: "FETCH_ACCOUNT_CASH_TRANSACTIONS_REQUEST",
  FETCH_ACCOUNT_CASH_TRANSACTIONS_SUCCESS: "FETCH_ACCOUNT_CASH_TRANSACTIONS_SUCCESS",
  FETCH_ACCOUNT_CASH_TRANSACTIONS_ERROR: "FETCH_ACCOUNT_CASH_TRANSACTIONS_ERROR",

  FETCH_ACCOUNT_LATEST_TRANSFERS_REQUEST: "FETCH_ACCOUNT_LATEST_TRANSFERS_REQUEST",
  FETCH_ACCOUNT_LATEST_TRANSFERS_SUCCESS: "FETCH_ACCOUNT_LATEST_TRANSFERS_SUCCESS",
  FETCH_ACCOUNT_LATEST_TRANSFERS_ERROR: "FETCH_ACCOUNT_LATEST_TRANSFERS_ERROR",

  CREATE_CASH_TRANSACTION_REQUEST: "CREATE_CASH_TRANSACTION_REQUEST",
  CREATE_CASH_TRANSACTION_SUCCESS: "CREATE_CASH_TRANSACTION_SUCCESS",
  CREATE_CASH_TRANSACTION_ERROR: "CREATE_CASH_TRANSACTION_ERROR",

  /****************************FETCH CITIES CONSTANTS**********************************/
  FETCH_CITIES_REQUEST: "FETCH_CITIES_REQUEST",
  FETCH_CITIES_SUCCESS: "FETCH_CITIES_SUCCESS",
  FETCH_CITIES_ERROR: "FETCH_CITIES_ERROR",

  FETCH_CITY_REQUEST: "FETCH_CITY_REQUEST",
  FETCH_CITY_SUCCESS: "FETCH_CITY_SUCCESS",
  FETCH_CITY_ERROR: "FETCH_CITY_ERROR",

  CREATE_CITY_REQUEST: "CREATE_CITY_REQUEST",
  CREATE_CITY_SUCCESS: "CREATE_CITY_SUCCESS",
  CREATE_CITY_ERROR: "CREATE_CITY_ERROR",

  UPDATE_CITY_REQUEST: "UPDATE_CITY_REQUEST",
  UPDATE_CITY_SUCCESS: "UPDATE_CITY_SUCCESS",
  UPDATE_CITY_ERROR: "UPDATE_CITY_ERROR",

  /***************************************CREDIT CARDS CONSTANTS*******************************************/
  FETCH_CREDIT_CARDS_REQUEST: "FETCH_CREDIT_CARDS_REQUEST",
  FETCH_CREDIT_CARDS_SUCCESS: "FETCH_CREDIT_CARDS_SUCCESS",
  FETCH_CREDIT_CARDS_ERROR: "FETCH_CREDIT_CARDS_ERROR",

  FETCH_CREDIT_CARD_REQUEST: "FETCH_CREDIT_CARD_REQUEST",
  FETCH_CREDIT_CARD_SUCCESS: "FETCH_CREDIT_CARD_SUCCESS",
  FETCH_CREDIT_CARD_ERROR: "FETCH_CREDIT_CARD_ERROR",

  CREATE_CREDIT_CARD_REQUEST: "CREATE_CREDIT_CARD_REQUEST",
  CREATE_CREDIT_CARD_SUCCESS: "CREATE_CREDIT_CARD_SUCCESS",
  CREATE_CREDIT_CARD_ERROR: "CREATE_CREDIT_CARD_ERROR",

  UPDATE_CREDIT_CARD_REQUEST: "UPDATE_CREDIT_CARD_REQUEST",
  UPDATE_CREDIT_CARD_SUCCESS: "UPDATE_CREDIT_CARD_SUCCESS",
  UPDATE_CREDIT_CARD_ERROR: "UPDATE_CREDIT_CARD_ERROR",

  /***************************************CUSTOMERS CONSTANTS*******************************************/
  FETCH_CUSTOMER_REQUEST: "FETCH_CUSTOMER_REQUEST",
  FETCH_CUSTOMER_SUCCESS: "FETCH_CUSTOMER_SUCCESS",
  FETCH_CUSTOMER_ERROR: "FETCH_CUSTOMER_ERROR",

  CREATE_CUSTOMER_REQUEST: "CREATE_CUSTOMER_REQUEST",
  CREATE_CUSTOMER_SUCCESS: "CREATE_CUSTOMER_SUCCESS",
  CREATE_CUSTOMER_ERROR: "CREATE_CUSTOMER_ERROR",

  UPDATE_CUSTOMER_REQUEST: "UPDATE_CUSTOMER_REQUEST",
  UPDATE_CUSTOMER_SUCCESS: "UPDATE_CUSTOMER_SUCCESS",
  UPDATE_CUSTOMER_ERROR: "UPDATE_CUSTOMER_ERROR",

  /****************************FETCH DISTRICTS CONSTANTS**********************************/
  FETCH_DISTRICTS_REQUEST: "FETCH_DISTRICTS_REQUEST",
  FETCH_DISTRICTS_SUCCESS: "FETCH_DISTRICTS_SUCCESS",
  FETCH_DISTRICTS_ERROR: "FETCH_DISTRICTS_ERROR",

  FETCH_DISTRICT_REQUEST: "FETCH_DISTRICT_REQUEST",
  FETCH_DISTRICT_SUCCESS: "FETCH_DISTRICT_SUCCESS",
  FETCH_DISTRICT_ERROR: "FETCH_DISTRICT_ERROR",

  CREATE_DISTRICT_REQUEST: "CREATE_DISTRICT_REQUEST",
  CREATE_DISTRICT_SUCCESS: "CREATE_DISTRICT_SUCCESS",
  CREATE_DISTRICT_ERROR: "CREATE_DISTRICT_ERROR",

  UPDATE_DISTRICT_REQUEST: "UPDATE_DISTRICT_REQUEST",
  UPDATE_DISTRICT_SUCCESS: "UPDATE_DISTRICT_SUCCESS",
  UPDATE_DISTRICT_ERROR: "UPDATE_DISTRICT_ERROR",

  /************************************FAST TRANSACTIONS CONSTANTS*********************************/
  FETCH_ACCOUNT_FAST_TRANSACTIONS_REQUEST: "FETCH_ACCOUNT_FAST_TRANSACTIONS_REQUEST",
  FETCH_ACCOUNT_FAST_TRANSACTIONS_SUCCESS: "FETCH_ACCOUNT_FAST_TRANSACTIONS_SUCCESS",
  FETCH_ACCOUNT_FAST_TRANSACTIONS_ERROR: "FETCH_ACCOUNT_FAST_TRANSACTIONS_ERROR",

  CREATE_FAST_TRANSACTION_REQUEST: "CREATE_FAST_TRANSACTION_REQUEST",
  CREATE_FAST_TRANSACTION_SUCCESS: "CREATE_FAST_TRANSACTION_SUCCESS",
  CREATE_FAST_TRANSACTION_ERROR: "CREATE_FAST_TRANSACTIONS_ERROR",

  UPDATE_FAST_TRANSACTION_REQUEST: "UPDATE_FAST_TRANSACTION_REQUEST",
  UPDATE_FAST_TRANSACTION_SUCCESS: "UPDATE_FAST_TRANSACTION_SUCCESS",
  UPDATE_FAST_TRANSACTION_ERROR: "UPDATE_FAST_TRANSACTIONS_ERROR",

  /************************************ADMINISTRATION CONSTANTS**********************************/
  FETCH_ROLES_REQUEST: "FETCH_ROLES_REQUEST",
  FETCH_ROLES_SUCCESS: "FETCH_ROLES_SUCCESS",
  FETCH_ROLES_ERROR: "FETCH_ROLES_ERROR",

  FETCH_USERS_IN_ROLE_REQUEST: "FETCH_USERS_IN_ROLE_REQUEST",
  FETCH_USERS_IN_ROLE_SUCCESS: "FETCH_USERS_IN_ROLE_SUCCESS",
  FETCH_USERS_IN_ROLE_ERROR: "FETCH_USERS_IN_ROLE_ERROR",

  EDIT_USERS_IN_ROLE_REQUEST: "EDIT_USERS_IN_ROLE_REQUEST",
  EDIT_USERS_IN_ROLE_SUCCESS: "EDIT_USERS_IN_ROLE_SUCCESS",
  EDIT_USERS_IN_ROLE_ERROR: "EDIT_USERS_IN_ROLE_ERROR",

  CREATE_ROLES_REQUEST: "CREATE_ROLES_REQUEST",
  CREATE_ROLES_SUCCESS: "CREATE_ROLES_SUCCESS",
  CREATE_ROLES_ERROR: "CREATE_ROLES_ERROR",
};
